// <auto-generated>
/*
 * Moira Alert
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * Contact: kontur.moira.alert@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Moira.ApiClient.Client;

namespace Moira.ApiClient.Model
{
    /// <summary>
    /// DtoContactNoisinessList
    /// </summary>
    public partial class DtoContactNoisinessList : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DtoContactNoisinessList" /> class.
        /// </summary>
        /// <param name="list">List of entities.</param>
        /// <param name="page">Page number.</param>
        /// <param name="size">Size is the amount of entities per Page.</param>
        /// <param name="total">Total amount of entities in the database.</param>
        [JsonConstructor]
        public DtoContactNoisinessList(List<DtoContactNoisiness> list, long page, long size, long total)
        {
            List = list;
            Page = page;
            Size = size;
            Total = total;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// List of entities.
        /// </summary>
        /// <value>List of entities.</value>
        [JsonPropertyName("list")]
        public List<DtoContactNoisiness> List { get; set; }

        /// <summary>
        /// Page number.
        /// </summary>
        /// <value>Page number.</value>
        /* <example>0</example> */
        [JsonPropertyName("page")]
        public long Page { get; set; }

        /// <summary>
        /// Size is the amount of entities per Page.
        /// </summary>
        /// <value>Size is the amount of entities per Page.</value>
        /* <example>100</example> */
        [JsonPropertyName("size")]
        public long Size { get; set; }

        /// <summary>
        /// Total amount of entities in the database.
        /// </summary>
        /// <value>Total amount of entities in the database.</value>
        /* <example>10</example> */
        [JsonPropertyName("total")]
        public long Total { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DtoContactNoisinessList {\n");
            sb.Append("  List: ").Append(List).Append("\n");
            sb.Append("  Page: ").Append(Page).Append("\n");
            sb.Append("  Size: ").Append(Size).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DtoContactNoisinessList" />
    /// </summary>
    public class DtoContactNoisinessListJsonConverter : JsonConverter<DtoContactNoisinessList>
    {
        /// <summary>
        /// Deserializes json to <see cref="DtoContactNoisinessList" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DtoContactNoisinessList Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<DtoContactNoisiness>> list = default;
            Option<long?> page = default;
            Option<long?> size = default;
            Option<long?> total = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "list":
                            list = new Option<List<DtoContactNoisiness>>(JsonSerializer.Deserialize<List<DtoContactNoisiness>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "page":
                            page = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "size":
                            size = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "total":
                            total = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!list.IsSet)
                throw new ArgumentException("Property is required for class DtoContactNoisinessList.", nameof(list));

            if (!page.IsSet)
                throw new ArgumentException("Property is required for class DtoContactNoisinessList.", nameof(page));

            if (!size.IsSet)
                throw new ArgumentException("Property is required for class DtoContactNoisinessList.", nameof(size));

            if (!total.IsSet)
                throw new ArgumentException("Property is required for class DtoContactNoisinessList.", nameof(total));

            if (list.IsSet && list.Value == null)
                throw new ArgumentNullException(nameof(list), "Property is not nullable for class DtoContactNoisinessList.");

            if (page.IsSet && page.Value == null)
                throw new ArgumentNullException(nameof(page), "Property is not nullable for class DtoContactNoisinessList.");

            if (size.IsSet && size.Value == null)
                throw new ArgumentNullException(nameof(size), "Property is not nullable for class DtoContactNoisinessList.");

            if (total.IsSet && total.Value == null)
                throw new ArgumentNullException(nameof(total), "Property is not nullable for class DtoContactNoisinessList.");

            return new DtoContactNoisinessList(list.Value, page.Value.Value, size.Value.Value, total.Value.Value);
        }

        /// <summary>
        /// Serializes a <see cref="DtoContactNoisinessList" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dtoContactNoisinessList"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DtoContactNoisinessList dtoContactNoisinessList, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, dtoContactNoisinessList, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DtoContactNoisinessList" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dtoContactNoisinessList"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DtoContactNoisinessList dtoContactNoisinessList, JsonSerializerOptions jsonSerializerOptions)
        {
            if (dtoContactNoisinessList.List == null)
                throw new ArgumentNullException(nameof(dtoContactNoisinessList.List), "Property is required for class DtoContactNoisinessList.");

            writer.WritePropertyName("list");
            JsonSerializer.Serialize(writer, dtoContactNoisinessList.List, jsonSerializerOptions);
            writer.WriteNumber("page", dtoContactNoisinessList.Page);

            writer.WriteNumber("size", dtoContactNoisinessList.Size);

            writer.WriteNumber("total", dtoContactNoisinessList.Total);
        }
    }
}
