// <auto-generated>
/*
 * Moira Alert
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * Contact: kontur.moira.alert@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Moira.ApiClient.Client;

namespace Moira.ApiClient.Model
{
    /// <summary>
    /// DtoContactEventItem
    /// </summary>
    public partial class DtoContactEventItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DtoContactEventItem" /> class.
        /// </summary>
        /// <param name="metric">metric</param>
        /// <param name="oldState">oldState</param>
        /// <param name="state">state</param>
        /// <param name="timestamp">timestamp</param>
        /// <param name="triggerId">triggerId</param>
        [JsonConstructor]
        public DtoContactEventItem(string metric, string oldState, string state, long timestamp, string triggerId)
        {
            Metric = metric;
            OldState = oldState;
            State = state;
            Timestamp = timestamp;
            TriggerId = triggerId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Metric
        /// </summary>
        [JsonPropertyName("metric")]
        public string Metric { get; set; }

        /// <summary>
        /// Gets or Sets OldState
        /// </summary>
        [JsonPropertyName("old_state")]
        public string OldState { get; set; }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [JsonPropertyName("state")]
        public string State { get; set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [JsonPropertyName("timestamp")]
        public long Timestamp { get; set; }

        /// <summary>
        /// Gets or Sets TriggerId
        /// </summary>
        [JsonPropertyName("trigger_id")]
        public string TriggerId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DtoContactEventItem {\n");
            sb.Append("  Metric: ").Append(Metric).Append("\n");
            sb.Append("  OldState: ").Append(OldState).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  TriggerId: ").Append(TriggerId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DtoContactEventItem" />
    /// </summary>
    public class DtoContactEventItemJsonConverter : JsonConverter<DtoContactEventItem>
    {
        /// <summary>
        /// Deserializes json to <see cref="DtoContactEventItem" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DtoContactEventItem Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> metric = default;
            Option<string> oldState = default;
            Option<string> state = default;
            Option<long?> timestamp = default;
            Option<string> triggerId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "metric":
                            metric = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "old_state":
                            oldState = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "state":
                            state = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "timestamp":
                            timestamp = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "trigger_id":
                            triggerId = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!metric.IsSet)
                throw new ArgumentException("Property is required for class DtoContactEventItem.", nameof(metric));

            if (!oldState.IsSet)
                throw new ArgumentException("Property is required for class DtoContactEventItem.", nameof(oldState));

            if (!state.IsSet)
                throw new ArgumentException("Property is required for class DtoContactEventItem.", nameof(state));

            if (!timestamp.IsSet)
                throw new ArgumentException("Property is required for class DtoContactEventItem.", nameof(timestamp));

            if (!triggerId.IsSet)
                throw new ArgumentException("Property is required for class DtoContactEventItem.", nameof(triggerId));

            if (metric.IsSet && metric.Value == null)
                throw new ArgumentNullException(nameof(metric), "Property is not nullable for class DtoContactEventItem.");

            if (oldState.IsSet && oldState.Value == null)
                throw new ArgumentNullException(nameof(oldState), "Property is not nullable for class DtoContactEventItem.");

            if (state.IsSet && state.Value == null)
                throw new ArgumentNullException(nameof(state), "Property is not nullable for class DtoContactEventItem.");

            if (timestamp.IsSet && timestamp.Value == null)
                throw new ArgumentNullException(nameof(timestamp), "Property is not nullable for class DtoContactEventItem.");

            if (triggerId.IsSet && triggerId.Value == null)
                throw new ArgumentNullException(nameof(triggerId), "Property is not nullable for class DtoContactEventItem.");

            return new DtoContactEventItem(metric.Value, oldState.Value, state.Value, timestamp.Value.Value, triggerId.Value);
        }

        /// <summary>
        /// Serializes a <see cref="DtoContactEventItem" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dtoContactEventItem"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DtoContactEventItem dtoContactEventItem, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, dtoContactEventItem, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DtoContactEventItem" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dtoContactEventItem"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DtoContactEventItem dtoContactEventItem, JsonSerializerOptions jsonSerializerOptions)
        {
            if (dtoContactEventItem.Metric == null)
                throw new ArgumentNullException(nameof(dtoContactEventItem.Metric), "Property is required for class DtoContactEventItem.");

            if (dtoContactEventItem.OldState == null)
                throw new ArgumentNullException(nameof(dtoContactEventItem.OldState), "Property is required for class DtoContactEventItem.");

            if (dtoContactEventItem.State == null)
                throw new ArgumentNullException(nameof(dtoContactEventItem.State), "Property is required for class DtoContactEventItem.");

            if (dtoContactEventItem.TriggerId == null)
                throw new ArgumentNullException(nameof(dtoContactEventItem.TriggerId), "Property is required for class DtoContactEventItem.");

            writer.WriteString("metric", dtoContactEventItem.Metric);

            writer.WriteString("old_state", dtoContactEventItem.OldState);

            writer.WriteString("state", dtoContactEventItem.State);

            writer.WriteNumber("timestamp", dtoContactEventItem.Timestamp);

            writer.WriteString("trigger_id", dtoContactEventItem.TriggerId);
        }
    }
}
