// <auto-generated>
/*
 * Moira Alert
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * Contact: kontur.moira.alert@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Moira.ApiClient.Client;

namespace Moira.ApiClient.Model
{
    /// <summary>
    /// DtoNotificationsList
    /// </summary>
    public partial class DtoNotificationsList : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DtoNotificationsList" /> class.
        /// </summary>
        /// <param name="list">list</param>
        /// <param name="total">total</param>
        [JsonConstructor]
        public DtoNotificationsList(List<MoiraScheduledNotification> list, long total)
        {
            List = list;
            Total = total;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets List
        /// </summary>
        [JsonPropertyName("list")]
        public List<MoiraScheduledNotification> List { get; set; }

        /// <summary>
        /// Gets or Sets Total
        /// </summary>
        /* <example>0</example> */
        [JsonPropertyName("total")]
        public long Total { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DtoNotificationsList {\n");
            sb.Append("  List: ").Append(List).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DtoNotificationsList" />
    /// </summary>
    public class DtoNotificationsListJsonConverter : JsonConverter<DtoNotificationsList>
    {
        /// <summary>
        /// Deserializes json to <see cref="DtoNotificationsList" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DtoNotificationsList Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<MoiraScheduledNotification>> list = default;
            Option<long?> total = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "list":
                            list = new Option<List<MoiraScheduledNotification>>(JsonSerializer.Deserialize<List<MoiraScheduledNotification>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "total":
                            total = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!list.IsSet)
                throw new ArgumentException("Property is required for class DtoNotificationsList.", nameof(list));

            if (!total.IsSet)
                throw new ArgumentException("Property is required for class DtoNotificationsList.", nameof(total));

            if (list.IsSet && list.Value == null)
                throw new ArgumentNullException(nameof(list), "Property is not nullable for class DtoNotificationsList.");

            if (total.IsSet && total.Value == null)
                throw new ArgumentNullException(nameof(total), "Property is not nullable for class DtoNotificationsList.");

            return new DtoNotificationsList(list.Value, total.Value.Value);
        }

        /// <summary>
        /// Serializes a <see cref="DtoNotificationsList" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dtoNotificationsList"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DtoNotificationsList dtoNotificationsList, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, dtoNotificationsList, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DtoNotificationsList" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dtoNotificationsList"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DtoNotificationsList dtoNotificationsList, JsonSerializerOptions jsonSerializerOptions)
        {
            if (dtoNotificationsList.List == null)
                throw new ArgumentNullException(nameof(dtoNotificationsList.List), "Property is required for class DtoNotificationsList.");

            writer.WritePropertyName("list");
            JsonSerializer.Serialize(writer, dtoNotificationsList.List, jsonSerializerOptions);
            writer.WriteNumber("total", dtoNotificationsList.Total);
        }
    }
}
