// <auto-generated>
/*
 * Moira Alert
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * Contact: kontur.moira.alert@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Moira.ApiClient.Client;

namespace Moira.ApiClient.Model
{
    /// <summary>
    /// DtoPatternMetrics
    /// </summary>
    public partial class DtoPatternMetrics : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DtoPatternMetrics" /> class.
        /// </summary>
        /// <param name="metrics">metrics</param>
        /// <param name="pattern">pattern</param>
        /// <param name="retention">retention</param>
        [JsonConstructor]
        public DtoPatternMetrics(Dictionary<string, List<MoiraMetricValue>> metrics, string pattern, Dictionary<string, int> retention)
        {
            Metrics = metrics;
            Pattern = pattern;
            Retention = retention;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Metrics
        /// </summary>
        [JsonPropertyName("metrics")]
        public Dictionary<string, List<MoiraMetricValue>> Metrics { get; set; }

        /// <summary>
        /// Gets or Sets Pattern
        /// </summary>
        [JsonPropertyName("pattern")]
        public string Pattern { get; set; }

        /// <summary>
        /// Gets or Sets Retention
        /// </summary>
        [JsonPropertyName("retention")]
        public Dictionary<string, int> Retention { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DtoPatternMetrics {\n");
            sb.Append("  Metrics: ").Append(Metrics).Append("\n");
            sb.Append("  Pattern: ").Append(Pattern).Append("\n");
            sb.Append("  Retention: ").Append(Retention).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DtoPatternMetrics" />
    /// </summary>
    public class DtoPatternMetricsJsonConverter : JsonConverter<DtoPatternMetrics>
    {
        /// <summary>
        /// Deserializes json to <see cref="DtoPatternMetrics" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DtoPatternMetrics Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Dictionary<string, List<MoiraMetricValue>>> metrics = default;
            Option<string> pattern = default;
            Option<Dictionary<string, int>> retention = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "metrics":
                            metrics = new Option<Dictionary<string, List<MoiraMetricValue>>>(JsonSerializer.Deserialize<Dictionary<string, List<MoiraMetricValue>>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "pattern":
                            pattern = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "retention":
                            retention = new Option<Dictionary<string, int>>(JsonSerializer.Deserialize<Dictionary<string, int>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!metrics.IsSet)
                throw new ArgumentException("Property is required for class DtoPatternMetrics.", nameof(metrics));

            if (!pattern.IsSet)
                throw new ArgumentException("Property is required for class DtoPatternMetrics.", nameof(pattern));

            if (!retention.IsSet)
                throw new ArgumentException("Property is required for class DtoPatternMetrics.", nameof(retention));

            if (metrics.IsSet && metrics.Value == null)
                throw new ArgumentNullException(nameof(metrics), "Property is not nullable for class DtoPatternMetrics.");

            if (pattern.IsSet && pattern.Value == null)
                throw new ArgumentNullException(nameof(pattern), "Property is not nullable for class DtoPatternMetrics.");

            if (retention.IsSet && retention.Value == null)
                throw new ArgumentNullException(nameof(retention), "Property is not nullable for class DtoPatternMetrics.");

            return new DtoPatternMetrics(metrics.Value, pattern.Value, retention.Value);
        }

        /// <summary>
        /// Serializes a <see cref="DtoPatternMetrics" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dtoPatternMetrics"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DtoPatternMetrics dtoPatternMetrics, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, dtoPatternMetrics, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DtoPatternMetrics" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dtoPatternMetrics"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DtoPatternMetrics dtoPatternMetrics, JsonSerializerOptions jsonSerializerOptions)
        {
            if (dtoPatternMetrics.Metrics == null)
                throw new ArgumentNullException(nameof(dtoPatternMetrics.Metrics), "Property is required for class DtoPatternMetrics.");

            if (dtoPatternMetrics.Pattern == null)
                throw new ArgumentNullException(nameof(dtoPatternMetrics.Pattern), "Property is required for class DtoPatternMetrics.");

            if (dtoPatternMetrics.Retention == null)
                throw new ArgumentNullException(nameof(dtoPatternMetrics.Retention), "Property is required for class DtoPatternMetrics.");

            writer.WritePropertyName("metrics");
            JsonSerializer.Serialize(writer, dtoPatternMetrics.Metrics, jsonSerializerOptions);
            writer.WriteString("pattern", dtoPatternMetrics.Pattern);

            writer.WritePropertyName("retention");
            JsonSerializer.Serialize(writer, dtoPatternMetrics.Retention, jsonSerializerOptions);
        }
    }
}
